name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-e2e:
    name: Build, Unit & E2E
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Unit tests (Jest)
        run: npm run test -- --ci --maxWorkers=50%

      - name: Build (production)
        run: npm run build

      - name: E2E (Cypress headless)
        # Usa el script integrado que levanta el server y ejecuta las pruebas
        run: npm run e2e:full

      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload coverage (if generated)
        if: success() && hashFiles('coverage/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  # Ejemplo de job separado para futuras auditorías de rendimiento
  # perf-audit:
  #   name: Performance (Lighthouse)
  #   needs: build-test-e2e
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install deps
  #       run: npm ci
  #       working-directory: sw-vehicles-ecommerce
  #     - name: Build
  #       run: npm run build
  #       working-directory: sw-vehicles-ecommerce
  #     - name: Lighthouse CI (placeholder)
  #       run: echo "Integrar lighthouse-ci aquí"
